"""create instruments, daily_closes, price_snapshots

Revision ID: 7d181e72df99
Revises:
Create Date: 2026-10-08 19:24:06.321329
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7d181e72df99"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("asset_class", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
        sa.UniqueConstraint("symbol", name=op.f("uq_instruments_symbol")),
    )
    op.create_table(
        "daily_closes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"], ["instruments.symbol"], name=op.f("fk_daily_closes_symbol_instruments")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_closes")),
        sa.UniqueConstraint("symbol", "day", name=op.f("uq_daily_closes_symbol_day")),
    )
    op.create_table(
        "price_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["symbol"], ["instruments.symbol"], name=op.f("fk_price_snapshots_symbol_instruments")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_snapshots")),
        sa.UniqueConstraint(
            "symbol", "observed_at", name=op.f("uq_price_snapshots_symbol_observed_at")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("price_snapshots")
    op.drop_table("daily_closes")
    op.drop_table("instruments")
    # ### end Alembic commands ###
